[project]
name = "MrBenn Toolbar Plugin"
authors = [{name = "Andy Woods", email = "andytwoods@gmail.com"}]
dynamic = ["version", "description"]

[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"